"""
Django settings for pet_insurance project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-23szz8bfylk8!=cv+^h!l1l9+=%vj8+(15v+)dsuh*y-be4@z*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['*']  # Will be restricted by Heroku app domain


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pet_insurance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pet_insurance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use PostgreSQL on Heroku
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.parse(os.environ['DATABASE_URL'])


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files - Use S3 (Bucketeer) on Heroku, local filesystem for development
if 'BUCKETEER_BUCKET_NAME' in os.environ:
    # Use S3 storage via Bucketeer for media files only
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    AWS_ACCESS_KEY_ID = os.environ.get('BUCKETEER_AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('BUCKETEER_AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('BUCKETEER_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('BUCKETEER_AWS_REGION', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    # Bucketeer buckets don't support ACLs - remove this setting
    # AWS_DEFAULT_ACL = 'public-read'  # Commented out - Bucketeer doesn't support ACLs
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    AWS_LOCATION = 'media'  # Store all media files in 'media' folder in S3
    
    # Media files
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    MEDIA_ROOT = 'media/'
else:
    # Local development - use local filesystem
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Viva Wallet Configuration
# Environment variables for production security
VIVA_WALLET_CLIENT_ID = os.environ.get('VIVA_WALLET_CLIENT_ID', '')
VIVA_WALLET_CLIENT_SECRET = os.environ.get('VIVA_WALLET_CLIENT_SECRET', '')
VIVA_WALLET_SOURCE_CODE = os.environ.get('VIVA_WALLET_SOURCE_CODE', '')

# Set to True for production, False for demo environment
VIVA_WALLET_PRODUCTION = os.environ.get('VIVA_WALLET_PRODUCTION', 'False').lower() == 'true'

# Site URL for QR code generation
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# Logging configuration for payment processing
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'main.viva_wallet': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'main.payment_views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'main.email_utils': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Add file handler only if logs directory exists (for local development)
logs_dir = BASE_DIR / 'logs'
if logs_dir.exists() or not os.environ.get('DYNO'):  # DYNO is set on Heroku
    try:
        logs_dir.mkdir(exist_ok=True)
        LOGGING['handlers']['file'] = {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': logs_dir / 'payments.log',
        }
        # Add file handler to loggers
        for logger_name in ['main.viva_wallet', 'main.payment_views', 'main.email_utils']:
            if 'file' not in LOGGING['loggers'][logger_name]['handlers']:
                LOGGING['loggers'][logger_name]['handlers'].append('file')
    except (OSError, PermissionError):
        pass  # Skip file logging if directory can't be created

# Email Configuration
# Use custom backend that disables SSL verification for self-signed certificates (common with Plesk)
# For local development, use console backend to print emails to console
if DEBUG and not os.environ.get('EMAIL_BACKEND'):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'pet_insurance.custom_email_backend.CustomEmailBackend')

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.hostinger.com')  # Hostinger SMTP server
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))  # SSL port for Hostinger
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'True').lower() == 'true'  # Use SSL for port 465
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False').lower() == 'true'  # Use TLS for port 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'application@pet-insurance.gr')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'application@pet-insurance.gr')
COMPANY_EMAIL = os.environ.get('COMPANY_EMAIL', 'info@hoolie.gr')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [
    "https://app.pet-insurance.gr",
    "https://*.herokuapp.com",  # fallback for Heroku's internal domain
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
