# Generated by Django 4.2.7 on 2025-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20)),
                ('payment_code', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('afm', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pet_name', models.CharField(blank=True, max_length=100)),
                ('pet_type', models.CharField(blank=True, choices=[('dog', 'Σκύλος'), ('cat', 'Γάτα')], max_length=10)),
                ('pet_gender', models.CharField(blank=True, choices=[('male', 'Αρσενικό'), ('female', 'Θηλυκό')], max_length=10)),
                ('pet_breed', models.CharField(blank=True, max_length=200)),
                ('pet_birthdate', models.DateField(blank=True, null=True)),
                ('pet_weight_category', models.CharField(blank=True, max_length=10)),
                ('microchip_number', models.CharField(blank=True, max_length=50)),
                ('has_second_pet', models.BooleanField(default=False)),
                ('second_pet_name', models.CharField(blank=True, max_length=100)),
                ('second_pet_type', models.CharField(blank=True, max_length=10)),
                ('second_pet_gender', models.CharField(blank=True, max_length=10)),
                ('second_pet_breed', models.CharField(blank=True, max_length=200)),
                ('second_pet_birthdate', models.DateField(blank=True, null=True)),
                ('second_pet_weight_category', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(blank=True, choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('health_status', models.CharField(blank=True, max_length=20)),
                ('health_conditions', models.TextField(blank=True)),
                ('second_pet_health_status', models.CharField(blank=True, max_length=20)),
                ('second_pet_health_conditions', models.TextField(blank=True)),
                ('annual_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('six_month_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('three_month_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('submitted', 'Υποβλήθηκε'), ('approved', 'Εγκρίθηκε'), ('rejected', 'Απορρίφθηκε'), ('active', 'Ενεργό'), ('expired', 'Έληξε')], default='draft', max_length=20)),
                ('contract_generated', models.BooleanField(default=False)),
                ('contract_pdf_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Αίτηση Ασφάλισης',
                'verbose_name_plural': 'Αιτήσεις Ασφάλισης',
                'ordering': ['-created_at'],
            },
        ),
    ]
