# Generated by Django 4.2.7 on 2025-11-19 12:53

from django.db import migrations, models
import django.db.models.deletion
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_application_number_and_nullable_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('annual', 'Ετήσιο'), ('six_month', '6μηνο'), ('three_month', '3μηνο')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installments', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
                'ordering': ['plan_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='insuranceapplication',
            options={},
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='affiliate_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied from affiliate code', max_digits=10),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='afm',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='contract_pdf_path',
            field=models.CharField(blank=True, help_text='Contract PDF with all application data', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='health_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Υγιές'), ('problems', 'Με προβλήματα')], max_length=20),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='payment_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='pet_birthdate',
            field=models.DateField(default=date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='pet_breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='pet_gender',
            field=models.CharField(choices=[('male', 'Αρσενικό'), ('female', 'Θηλυκό')], max_length=10),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Σκύλος'), ('cat', 'Γάτα')], max_length=10),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='pet_weight_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='program',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='second_pet_breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='second_pet_gender',
            field=models.CharField(blank=True, choices=[('male', 'Αρσενικό'), ('female', 'Θηλυκό')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='second_pet_health_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='second_pet_health_status',
            field=models.CharField(blank=True, choices=[('healthy', 'Υγιές'), ('problems', 'Με προβλήματα')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='second_pet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='second_pet_type',
            field=models.CharField(blank=True, choices=[('dog', 'Σκύλος'), ('cat', 'Γάτα')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='second_pet_weight_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Προσχέδιο'), ('submitted', 'Υποβλήθηκε'), ('payment_pending', 'Εκκρεμής Πληρωμή'), ('payment_failed', 'Αποτυχία Πληρωμής'), ('paid', 'Πληρώθηκε'), ('approved', 'Εγκρίθηκε'), ('active', 'Ενεργό'), ('rejected', 'Απορρίφθηκε'), ('cancelled', 'Ακυρώθηκε'), ('contact_form', 'Φόρμα Επικοινωνίας')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='insuranceapplication',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('order_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(choices=[('annual', 'Ετήσια Πληρωμή'), ('six_month', '6μηνη Πληρωμή'), ('three_month', '3μηνη Πληρωμή')], default='annual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμής'), ('completed', 'Ολοκληρώθηκε'), ('failed', 'Αποτυχία'), ('cancelled', 'Ακυρώθηκε'), ('refunded', 'Επιστράφηκε'), ('partially_refunded', 'Μερικώς Επιστράφηκε')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, default='viva_wallet', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('viva_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('viva_order_code', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('webhook_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.insuranceapplication')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbassadorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The discount code (e.g., PARTNER2024)', max_length=50, unique=True)),
                ('code_type', models.CharField(choices=[('ambassador', 'Πρέσβης'), ('partner', 'Συνεργάτης')], default='partner', max_length=20)),
                ('name', models.CharField(help_text='Name of the ambassador/partner', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the code')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (e.g., 10.00 for 10%)', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount in euros (0 = use percentage)', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (null = no limit)', max_digits=10, null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this code can be used (null = unlimited)', null=True)),
                ('current_uses', models.IntegerField(default=0, help_text='Current number of times used')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Code valid from this date (null = no start date)', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Code valid until this date (null = no expiry)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Who created this code', max_length=200)),
            ],
            options={
                'verbose_name': 'Ambassador/Partner Code',
                'verbose_name_plural': 'Ambassador/Partner Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='main_ambass_code_7bd36c_idx')],
            },
        ),
    ]
