# Generated by Django 4.2.7 on 2025-11-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_petdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Uploaded pet photo', upload_to='pet_photos/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type of the file', max_length=50)),
                ('pet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_type', models.CharField(blank=True, choices=[('dog', 'Σκύλος'), ('cat', 'Γάτα')], max_length=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.insuranceapplication')),
            ],
            options={
                'verbose_name': 'Pet Photo',
                'verbose_name_plural': 'Pet Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
