# Generated by Django 4.2.7 on 2025-11-20 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_petphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_other_insured_pet', models.BooleanField(default=False, help_text='Α. Έχετε άλλο, ήδη ασφαλιζόμενο κατοικίδιο στο ίδιο ασφαλιστικό πρόγραμμα;')),
                ('has_been_denied_insurance', models.BooleanField(default=False, help_text='Β. Σας έχουν αρνηθεί ή ακυρώσει την ανανέωση ή σας έχουν ή αρνηθεί στο παρελθόν πρότασή σας')),
                ('has_special_terms_imposed', models.BooleanField(default=False, help_text='Γ. Σας έχουν επιβάλλει Ειδικούς Όρους στο παρελθόν')),
                ('pet_colors', models.CharField(blank=True, help_text='Χρώματα κατοικιδίου', max_length=200, null=True)),
                ('pet_weight', models.CharField(blank=True, help_text='Βάρος', max_length=50, null=True)),
                ('is_purebred', models.BooleanField(default=False, help_text='Καθαρόαιμο')),
                ('is_mixed', models.BooleanField(default=False, help_text='Ημίαιμο')),
                ('is_crossbreed', models.BooleanField(default=False, help_text='Διασταύρωση ράτσας')),
                ('special_breed_5_percent', models.BooleanField(default=False, help_text='Cane Corso, Dogo Argentino, Rottweiler (5% surcharge)')),
                ('special_breed_20_percent', models.BooleanField(default=False, help_text='Pit Bull, French Bulldog, English Bulldog, Chow Chow (20% surcharge)')),
                ('is_healthy', models.BooleanField(default=True, help_text='Α. Το κατοικίδιο είναι υγιές κατά την ημερομηνία αίτησης;')),
                ('is_healthy_details', models.TextField(blank=True, help_text='Εάν ΟΧΙ, περισσότερες λεπτομέρειες', null=True)),
                ('has_injury_illness_3_years', models.BooleanField(default=False, help_text='Β. Υπήρξε τραυματισμός, ασθένεια τα τελευταία 3 έτη;')),
                ('has_injury_illness_details', models.TextField(blank=True, help_text='Εάν ΝΑΙ, περισσότερες λεπτομέρειες', null=True)),
                ('has_surgical_procedure', models.BooleanField(default=False, help_text='Γ. Έχει υποβληθεί σε χειρουργική επέμβαση;')),
                ('has_surgical_procedure_details', models.TextField(blank=True, help_text='Εάν ΝΑΙ, περισσότερες λεπτομέρειες', null=True)),
                ('has_examination_findings', models.BooleanField(default=False, help_text='Δ. Έχει υποβληθεί σε εξέταση (ακτινογραφία, MRI, υπερηχογράφημα) και υπήρξαν ευρήματα;')),
                ('has_examination_findings_details', models.TextField(blank=True, help_text='Εάν ΝΑΙ, περισσότερες λεπτομέρειες', null=True)),
                ('is_sterilized', models.BooleanField(default=False, help_text='Ε. Έχει υποβληθεί σε στείρωση;')),
                ('is_vaccinated_leishmaniasis', models.BooleanField(default=False, help_text='Ζ. Το κατοικίδιο έχει εμβολιαστεί κατά της λεϊσμανίασης;')),
                ('follows_vaccination_program', models.BooleanField(default=True, help_text='Η. Ακολουθεί πιστά το πρόγραμμα εμβολιασμών;')),
                ('follows_vaccination_program_details', models.TextField(blank=True, help_text='Εάν ΟΧΙ, περισσότερες λεπτομέρειες', null=True)),
                ('has_hereditary_disease', models.BooleanField(default=False, help_text='Θ. Έχει το κατοικίδιο οποιαδήποτε κληρονομική ασθένεια;')),
                ('has_hereditary_disease_details', models.TextField(blank=True, help_text='Αν ΝΑΙ, αναφέρετε ποια/ποιες', null=True)),
                ('program', models.CharField(blank=True, choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('dynasty', 'Dynasty')], max_length=20, null=True)),
                ('additional_poisoning_coverage', models.BooleanField(default=False, help_text='Πρόσθετη Κάλυψη Δηλητηρίασης')),
                ('additional_blood_checkup', models.BooleanField(default=False, help_text='Επιπλέον Παροχή Προνομιακού Αιματολογικού Check-Up με 28€/έτος')),
                ('desired_start_date', models.DateField(blank=True, help_text='Επιθυμητή Έναρξη Ασφάλισης', null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Χρεωστική/Πιστωτική/Προπληρωμένη κάρτα'), ('bank_deposit', 'Τραπεζική κατάθεση'), ('cash', 'Μετρητά')], max_length=20, null=True)),
                ('payment_frequency', models.CharField(blank=True, choices=[('annual', 'Ετήσια Πληρωμή'), ('six_month', 'Εξάμηνη Πληρωμή')], max_length=20, null=True)),
                ('consent_terms_conditions', models.BooleanField(default=False, help_text='1. Γνωρίζω ότι στην ασφάλιση αυτή ισχύουν οι Γενικοί και Ειδικοί Όροι')),
                ('consent_info_document', models.BooleanField(default=False, help_text='2. Παρέλαβα το ενημερωτικό έντυπο')),
                ('consent_email_notifications', models.BooleanField(default=False, help_text='3. Ενημέρωση σχετικά με ασφάλιση μέσω E-mail')),
                ('consent_marketing', models.BooleanField(default=False, help_text='4. Ενημέρωση για διαφημιστικούς, εμπορικούς σκοπούς')),
                ('consent_data_processing', models.BooleanField(default=False, help_text='5. Ενημέρωση σχετικά με Επεξεργασία Προσωπικών Δεδομένων')),
                ('consent_pet_gov_platform', models.BooleanField(default=False, help_text='Συναίνεση για χρήση πλατφόρμας pet.gov.gr')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='main.insuranceapplication')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'ordering': ['-created_at'],
            },
        ),
    ]
