# Generated by Django 4.2.7 on 2025-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('annual', 'Ετήσια Πληρωμή'), ('six_month', 'Εξάμηνη Πληρωμή'), ('three_month', 'Τριμηνιαία Πληρωμή')], max_length=20, null=True),
        ),
    ]
