# Generated by Django 4.2.7 on 2025-12-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_questionnaire_payment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
